# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zentest-without-autotest}
  s.version = "4.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Davis"]
  s.date = %q{2010-06-06}
  s.executables = ["multigem", "zentest", "multiruby", "multiruby_setup"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "History.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/multigem",
     "bin/multiruby",
     "bin/multiruby_setup",
     "bin/zentest",
     "example_dot_autotest.rb",
     "lib/focus.rb",
     "lib/functional_test_matrix.rb",
     "lib/multiruby.rb",
     "lib/zentest.rb",
     "lib/zentest_mapping.rb",
     "test/helper.rb",
     "test/test_focus.rb",
     "test/test_zentest.rb",
     "test/test_zentest_mapping.rb",
     "zentest-without-autotest.gemspec"
  ]
  s.homepage = %q{http://github.com/grosser/zentest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ZenTest, without AutoTest and UnitDiff}
  s.test_files = [
    "test/helper.rb",
     "test/test_zentest.rb",
     "test/test_focus.rb",
     "test/test_zentest_mapping.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

